name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build & verify (format, checkstyle, spotbugs, tests, jacoco)
        run: ./mvnw -B verify

      - name: Upload unit test report (surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs
          path: target/spotbugs

      # ---- SonarCloud (optioneel) ----
      # We gebruiken env.* in de if, niet secrets.*, om de parserfout te vermijden.
      - name: SonarCloud Scan (optional)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        if: ${{ env.SONAR_TOKEN != '' }}
        run: |
          ./mvnw -B \
            -Dsonar.login="${SONAR_TOKEN}" \
            -Dsonar.organization="${SONAR_ORG}" \
            -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
            sonar:sonar
